apiVersion: apps/v1
kind: Deployment
metadata:
  name: resizer
  labels:
    app: resizer
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resizer
      version: v1
  template:
    metadata:
      labels:
        app: resizer
        version: v1
    spec:
      containers:
      - name: resizer
        image: jstrohm/ping:1
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: resizer
  labels:
    app: resizer
    service: resizer
spec:
  selector:
    app: resizer
  ports:
  - port: 8080
    targetPort: 8080
    name: http
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: resizer-sm
  labels:
    name: resizer
spec:
  selector:
    matchLabels:
      app: resizer
  endpoints:
    - port: http
      path: /metrics
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: resizer
spec:
  hosts:
  - resizer.decepticons.local
  gateways:
  - default/primary-gateway
  http:
  - match:
    - uri:
        prefix: "/"
    - port: 8080
    route:
    - destination:
        host: resizer.default.svc.cluster.local
        port:
          number: 8080
      weight: 100
